# This is a basic workflow that is manually triggered

name: r2m-pr2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - release

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: checkout
    
      - name: get date
        env:
          TZ: 'Asia/Tokyo'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H:%M')"
      
      - uses: repo-sync/pull-request@v2
        name: create r2m pr
        with:
          destination_branch: "main"
          pr_title: "r2m_${{steps.date.outputs.date}}"
          pr_body: "*An automated PR*"
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
