# This is a basic workflow that is manually triggered

name: r2m-pr2

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
    - release

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: get date
        env:
          TZ: 'Asia/Tokyo'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - name: Create r2m pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create -B "master" -t "r2m_${{steps.date.outputs.date}}" -b ""
