name: r2m-pr2

on:
  push:
    branches:
      - release

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: checkout

      - name: get date
        env:
          TZ: 'Asia/Tokyo'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%H:%M')"
      
      - name: log latest commits
        id: commit-list
        run: echo "::set-output name=commits::$(git log --pretty=format:%s '${{github.event.before}}...${{github.event.after}}')"

      - uses: repo-sync/pull-request@v2
        name: create r2m pr
        with:
          destination_branch: "main"
          pr_title: "r2m_${{steps.date.outputs.date}}"
          pr_body: |
            COMMIT_URL(s): ${{steps.commit-list.outputs.commits}}  
            Author(s): @${{github.actor}}   
            ## Check List
            - [ ] stg test
            ## Confirm after release
            - Announce in #account_web
            - release to prod
            - Confirm in #release_prod
            - test service
            - Monitoring #account_rollbar_v2
          pr_draft: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
