name: r2m-pr

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Script
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMENT_URL: ${{github.event.pull_request.comments_url}}
        run: |
          git checkout release
          .github/workflows/x2m.main.kts